"""Validate ``data/calendar.csv`` and generate ``src/sambat/_table.py``.

The CSV is the single source of truth for Bikram Sambat month lengths. This
script checks every invariant described in ``data/README.md`` and writes a
compact, dependency-free Python module that the package imports at runtime.

Usage::

    python tools/build_table.py           # regenerate src/sambat/_table.py
    python tools/build_table.py --check   # fail if the generated file is stale
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "data" / "calendar.csv"
SOURCES_PATH = ROOT / "data" / "sources.toml"
TABLE_PATH = ROOT / "src" / "sambat" / "_table.py"

MIN_MONTH_DAYS = 29
MAX_MONTH_DAYS = 32
VALID_YEAR_LENGTHS = frozenset({365, 366})
EVIDENCE_LEVELS = frozenset({"verified", "consensus", "disputed"})
MONTH_COLUMNS = tuple(f"m{index:02d}" for index in range(1, 13))


class CalendarDataError(Exception):
    """Raised when ``data/calendar.csv`` violates an invariant."""


@dataclass(frozen=True, slots=True)
class YearRow:
    """One validated row of the calendar table."""

    bs_year: int
    baisakh1_ad: dt.date
    month_lengths: tuple[int, ...]
    evidence: str
    sources: tuple[str, ...]


def _parse_row(raw: dict[str, str], line: int) -> YearRow:
    try:
        lengths = tuple(int(raw[column]) for column in MONTH_COLUMNS)
        row = YearRow(
            bs_year=int(raw["bs_year"]),
            baisakh1_ad=dt.date.fromisoformat(raw["baisakh1_ad"]),
            month_lengths=lengths,
            evidence=raw["evidence"].strip(),
            sources=tuple(raw["sources"].split()),
        )
    except (KeyError, ValueError) as exc:
        message = f"line {line}: malformed row: {exc}"
        raise CalendarDataError(message) from exc
    return row


def _known_source_ids() -> set[str]:
    with SOURCES_PATH.open("rb") as handle:
        sources = tomllib.load(handle)
    return {entry["id"] for entry in sources.get("source", [])}


def load_rows() -> list[YearRow]:
    """Read and validate every row of ``data/calendar.csv``.

    Returns:
        The rows in ascending BS year order.

    Raises:
        CalendarDataError: If any invariant is violated.
    """
    with CSV_PATH.open(newline="", encoding="utf-8") as handle:
        rows = [_parse_row(raw, line) for line, raw in enumerate(csv.DictReader(handle), start=2)]
    if not rows:
        message = f"{CSV_PATH} contains no rows"
        raise CalendarDataError(message)

    source_ids = _known_source_ids()
    previous: YearRow | None = None
    for row in rows:
        _check_row(row, source_ids)
        if previous is not None:
            _check_continuity(previous, row)
        previous = row
    return rows


def _check_row(row: YearRow, source_ids: set[str]) -> None:
    year = row.bs_year
    for month, length in enumerate(row.month_lengths, start=1):
        if not MIN_MONTH_DAYS <= length <= MAX_MONTH_DAYS:
            message = f"BS {year} month {month}: length {length} outside 29..32"
            raise CalendarDataError(message)
    total = sum(row.month_lengths)
    if total not in VALID_YEAR_LENGTHS:
        message = f"BS {year}: year length {total} is not 365 or 366"
        raise CalendarDataError(message)
    if row.evidence not in EVIDENCE_LEVELS:
        message = f"BS {year}: unknown evidence level {row.evidence!r}"
        raise CalendarDataError(message)
    unknown = [source for source in row.sources if source not in source_ids]
    if unknown or not row.sources:
        message = f"BS {year}: sources {unknown or '(none)'} are not defined in sources.toml"
        raise CalendarDataError(message)


def _check_continuity(previous: YearRow, row: YearRow) -> None:
    if row.bs_year != previous.bs_year + 1:
        message = f"gap between BS {previous.bs_year} and BS {row.bs_year}"
        raise CalendarDataError(message)
    expected = previous.baisakh1_ad + dt.timedelta(days=sum(previous.month_lengths))
    if row.baisakh1_ad != expected:
        message = (
            f"BS {row.bs_year}: Baisakh 1 is {row.baisakh1_ad} but BS {previous.bs_year} "
            f"ends on {expected - dt.timedelta(days=1)}"
        )
        raise CalendarDataError(message)


def render(rows: list[YearRow]) -> str:
    """Render the generated ``_table.py`` module source.

    Args:
        rows: Validated rows in ascending year order.

    Returns:
        The module source code.
    """
    end_ordinal = rows[-1].baisakh1_ad.toordinal() + sum(rows[-1].month_lengths)
    lines = [
        '"""Bikram Sambat month lengths (generated file, do not edit).',
        "",
        "Generated by ``tools/build_table.py`` from ``data/calendar.csv``.",
        '"""',
        "",
        f"FIRST_YEAR = {rows[0].bs_year}",
        "",
        "#: Proleptic Gregorian ordinal of Baisakh 1 for each year, plus the ordinal",
        "#: of the day after the last supported day.",
        "YEAR_START_ORDINALS = (",
    ]
    lines += [f"    {row.baisakh1_ad.toordinal()},  # BS {row.bs_year}" for row in rows]
    lines += [f"    {end_ordinal},", ")", "", "MONTH_LENGTHS = ("]
    lines += [f"    {row.month_lengths},  # BS {row.bs_year}" for row in rows]
    lines += [")", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Validate the calendar data and (re)generate or check the table module.

    Args:
        argv: Command line arguments, without the program name.

    Returns:
        The process exit status.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if _table.py is stale")
    args = parser.parse_args(argv)

    try:
        rows = load_rows()
    except CalendarDataError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    source = render(rows)
    if args.check:
        current = TABLE_PATH.read_text(encoding="utf-8") if TABLE_PATH.exists() else ""
        if current != source:
            print(
                "error: src/sambat/_table.py is out of date; run python tools/build_table.py",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {len(rows)} years (BS {rows[0].bs_year}..{rows[-1].bs_year}) validated")
        return 0

    TABLE_PATH.write_text(source, encoding="utf-8")
    print(f"wrote {TABLE_PATH.relative_to(ROOT)} for BS {rows[0].bs_year}..{rows[-1].bs_year}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
